name: Deploy Python App to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy project to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "."
          target: "~/python-app"

      - name: SSH and run app
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/python-app
            python3 -m venv venv
            source venv/bin/activate
            export CHAT_ID=${{ secrets.CHAT_ID }}
            export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            pip install -r requirements.txt
            pkill -f main.py || true
            nohup python app/main.py > log.txt 2>&1 &
